In [1]:
import numpy as np

# 1. One-dimensional array

In [2]:
vector = np.arange(1, 11)

print(f'One dimensional integer array:')
print(vector)

One dimensional integer array:
[ 1  2  3  4  5  6  7  8  9 10]


# 2. Zero matrix

In [3]:
matrix = np.zeros((3, 3))

print(f'Zero Matrix 3x3:')
print(matrix)

Zero Matrix 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3. Random matrix 5x5

In [4]:
random_matrix = np.random.randint(0, 10, size=(5, 5))

print(f'Random matrix 5x5:')
print(random_matrix)

Random matrix 5x5:
[[4 8 8 7 3]
 [8 8 7 8 7]
 [4 7 7 8 6]
 [9 5 4 5 5]
 [5 2 9 0 0]]


# 4. Random real matrix 4x4

In [5]:
random_matrix = np.random.rand(4, 4)
np.set_printoptions(precision=2)

print(f'Random real matrix 4x4:')
print(random_matrix)

Random real matrix 4x4:
[[0.95 0.95 0.67 0.01]
 [0.13 0.01 0.44 0.38]
 [0.15 0.55 0.16 0.28]
 [0.96 0.65 0.4  0.23]]


# 5. Two one-dimensional matrix of length 5. Addition, Subtraction, Multiplication.

In [6]:
matrix_1 = np.random.randint(0, 10, size=(5,))
matrix_2 = np.random.randint(0, 10, size=(5,))

print(f'Original Matrix 1:')
print(matrix_1)
print(f'Original Matrix 2:')
print(matrix_2)

add = matrix_1 + matrix_2
print(f'Addition:')
print(add)

sub = matrix_1 - matrix_2
print(f'Subtraction:')
print(sub)

mult = matrix_1 * matrix_2
print(f'Multiplication:')
print(mult)

Original Matrix 1:
[9 6 2 3 6]
Original Matrix 2:
[8 7 6 2 8]
Addition:
[17 13  8  5 14]
Subtraction:
[ 1 -1 -4  1 -2]
Multiplication:
[72 42 12  6 48]


# 6. Two random vectors of size 7, dot product.

In [7]:
vector_1 = np.random.rand(7)
vector_2 = np.random.rand(7)
print(f'Original Vector 1:')
print(vector_1)
print(f'Original Vector 2:')
print(vector_2)
result = np.dot(vector_1, vector_2)
print(f'The dot product of two vectors:')
print(f'{result:.2f}')

Original Vector 1:
[0.1  0.06 0.21 0.99 0.14 0.09 0.96]
Original Vector 2:
[0.62 0.55 0.65 0.18 0.92 0.11 0.25]
The dot product of two vectors:
0.79


# 7. Two random matrices of size 2x2 and 2x3, integers between 1 and 10, multiplication.

In [8]:
matrix_1 = np.random.randint(1, 10, size=(2,2))
matrix_2 = np.random.randint(1, 10, size=(2,3))

print(f'Original Matrix 1:')
print(matrix_1)
print(f'Original Matrix 2:')
print(matrix_2)
mult = np.dot(matrix_1, matrix_2)
print(f'Multiplication of two matrix 2x2 and 2x3:')
print(mult)

Original Matrix 1:
[[9 6]
 [4 5]]
Original Matrix 2:
[[6 7 1]
 [9 5 6]]
Multiplication of two matrix 2x2 and 2x3:
[[108  93  45]
 [ 69  53  34]]


# 8. Random matrices of size 3x3, integers between 1 and 10, find inverse.

In [9]:
matrix = np.random.randint(1, 10, size=(3, 3))
invert = np.linalg.inv(matrix)

np.set_printoptions(precision=2, suppress=True)

print(f'Original Matrix:')
print(matrix)
print(f'Inverted matrix:')
print(invert)

Original Matrix:
[[2 2 5]
 [9 6 8]
 [3 8 5]]
Inverted matrix:
[[-0.21  0.19 -0.09]
 [-0.13 -0.03  0.18]
 [ 0.34 -0.06 -0.04]]


# 9. Random matrices of size 4x4, fill with real numbers between 0 and 1, transposition.

In [10]:
matrix = np.random.rand(4,4)
transp = matrix.T

print(f'Original Matrix:')
print(matrix)
print(f'Transposed Matrix:')
print(transp)

Original Matrix:
[[0.14 0.09 0.01 0.32]
 [0.88 0.77 0.7  0.23]
 [0.84 0.81 0.17 0.46]
 [0.22 0.59 0.43 0.94]]
Transposed Matrix:
[[0.14 0.88 0.84 0.22]
 [0.09 0.77 0.81 0.59]
 [0.01 0.7  0.17 0.43]
 [0.32 0.23 0.46 0.94]]


# 10. Random matrix 3x4 and vector 4, fill with real numbers between 1 and 10, multiply matrix by vector.

In [12]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4,))

result = np.dot(matrix, vector)

print(f'Original Matrix:')
print(matrix)
print(f'Original Vector:')
print(vector)
print(f'Multiply result:')
print(result)

Original Matrix:
[[ 3  7  7  2]
 [ 3 10  2 10]
 [ 9 10  8  7]]
Original Vector:
[10  1  5  4]
Multiply result:
[ 80  90 168]


# 11. Random matrix 2x3 and vector 3, fill with real numbers between 0 and 1, multiply matrix by vector.

In [13]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3,)

result = np.dot(matrix, vector)

print(f'Original Matrix:')
print(matrix)
print(f'Original Vector:')
print(vector)
print(f'Multiply result:')
print(result)

Original Matrix:
[[0.93 0.93 0.4 ]
 [0.8  0.65 0.12]]
Original Vector:
[0.25 0.07 0.51]
Multiply result:
[0.51 0.31]


# 12. Random matrix 2x2, fill with real numbers between 1 and 10, multiply.

In [15]:
matrix_1 = np.random.randint(1, 10, size=(2,2))
matrix_2 = np.random.randint(1, 10, size=(2,2))

print(f'Original Matrix 1:')
print(matrix_1)
print(f'Original Matrix 2:')
print(matrix_2)
mult = matrix_1 * matrix_2
print(f'Multiplication of two matrix 2x2 and 2x3:')
print(mult)

Original Matrix 1:
[[1 6]
 [4 8]]
Original Matrix 2:
[[2 3]
 [7 2]]
Multiplication of two matrix 2x2 and 2x3:
[[ 2 18]
 [28 16]]


# 13. Random matrix 2x2, fill with real numbers between 1 and 10, find their product.

In [16]:
matrix_1 = np.random.randint(1, 10, size=(2,2))
matrix_2 = np.random.randint(1, 10, size=(2,2))

print(f'Original Matrix 1:')
print(matrix_1)
print(f'Original Matrix 2:')
print(matrix_2)
mult = np.dot(matrix_1, matrix_2)
print(f'Multiplication of two matrix 2x2 and 2x3:')
print(mult)

Original Matrix 1:
[[9 1]
 [6 7]]
Original Matrix 2:
[[5 5]
 [7 2]]
Multiplication of two matrix 2x2 and 2x3:
[[52 47]
 [79 44]]


# 14. Random matrix 5x5, fill with real numbers between 1 and 100, sum.

In [18]:
matrix = np.random.randint(1, 100, size=(5,5))
result = matrix.max()

print(f'Original Matrix:')
print(matrix)
print(f'Result:')
print(result)

Original Matrix:
[[92 18 98 87 13]
 [92 75 30 87 91]
 [31 71 72 26 27]
 [69 87 30 20 28]
 [28 32 11  9 20]]
Result:
98


# 15. Random matrix 4x4, fill with real numbers between 1 and 10, find difference.

In [21]:
matrix_1 = np.random.randint(1, 10, size=(4,4))
matrix_2 = np.random.randint(1, 10, size=(4,4))
diff = matrix_1 - matrix_2

print(f'Original Matrix 1:')
print(matrix_1)
print(f'Original Matrix 2:')
print(matrix_2)
print(f'Difference:')
print(diff)

Original Matrix 1:
[[7 3 7 6]
 [9 2 2 8]
 [7 8 6 5]
 [6 1 2 8]]
Original Matrix 2:
[[9 3 1 1]
 [3 8 1 5]
 [1 2 7 7]
 [1 9 9 3]]
Difference:
[[-2  0  6  5]
 [ 6 -6  1  3]
 [ 6  6 -1 -2]
 [ 5 -8 -7  5]]


# 16. Random matrix 3x3, fill with real numbers between 0 and 1, find a column vector containing the sum of the elements of each row of the matrix.

In [23]:
matrix = np.random.rand(3, 3)

row_sums = matrix.sum(axis=1)
column_vector = row_sums.reshape(-1, 1)

print(f'Original Matrix:')
print(matrix)
print(f'Row sums:')
print(row_sums)
print(f'Column vector with sum of elements in each row:')
print(column_vector)

Original Matrix:
[[0.94 0.13 0.65]
 [0.78 0.82 0.48]
 [0.01 0.57 0.36]]
Row sums:
[1.72 2.08 0.94]
Column vector with sum of elements in each row:
[[1.72]
 [2.08]
 [0.94]]


# 17. Random matrix 3x3, create a matrix with the squares of these numbers.

In [24]:
matrix = np.random.randint(1, 11, size=(3, 4))

squared_matrix = matrix ** 2

print(f'Original Matrix (3x4):')
print(matrix)
print(f'Matrix with squares of the elements:')
print(squared_matrix)

Original Matrix (3x4):
[[10  7  8  1]
 [ 2  1  4  6]
 [10  1  9  5]]
Matrix with squares of the elements:
[[100  49  64   1]
 [  4   1  16  36]
 [100   1  81  25]]


# 18. Random vector 4, fill with real numbers between 1 and 50, find the vector of square roots of these numbers.

In [25]:
vector = np.random.randint(1, 51, size=4)

sqrt_vector = np.sqrt(vector)

print(f'Original Vector:')
print(vector)
print(f'Vector of square roots:')
print(sqrt_vector)

Original Vector:
[41 20 37 45]
Vector of square roots:
[6.4  4.47 6.08 6.71]
