In [3]:
import numpy as np

# 1 One-dimensional array

In [2]:
vector = np.arange(1, 11)

print(f'One dimensional integer array:')
print(vector)

One dimensional integer array.
[ 1  2  3  4  5  6  7  8  9 10]


# 2 Zero matrix

In [3]:
matrix = np.zeros((3, 3))

print(f'Zero Matrix 3x3:')
print(matrix)

Zero Matrix 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3 Random matrix 5x5

In [10]:
random_matrix = np.random.randint(0, 10, size=(5, 5))

print(f'Random matrix 5x5:')
print(random_matrix)

Random matrix 5x5:
[[0 7 7 7 9]
 [6 7 9 8 9]
 [1 4 3 0 5]
 [0 5 0 8 2]
 [9 4 1 8 3]]


# 4 Random real matrix 4x4

In [14]:
random_matrix = np.random.rand(4, 4)
np.set_printoptions(precision=2)

print(f'Random real matrix 4x4:')
print(random_matrix)

Random real matrix 4x4:
[[0.53 0.17 0.12 0.29]
 [0.45 0.05 0.4  0.17]
 [0.52 0.56 0.14 0.16]
 [0.94 0.89 0.66 0.95]]


# 5 Two one-dimensional matrix of length 5. Addition, Subtraction, Multiplication.

In [21]:
matrix_1 = np.random.randint(0, 10, size=(5,))
matrix_2 = np.random.randint(0, 10, size=(5,))

print(f'Matrix 1:')
print(matrix_1)
print(f'Matrix 2:')
print(matrix_2)

add = matrix_1 + matrix_2
print(f'Addition:')
print(add)

sub = matrix_1 - matrix_2
print(f'Subtraction:')
print(sub)

mult = matrix_1 * matrix_2
print(f'Multiplication:')
print(mult)

Matrix 1:
[0 3 0 2 6]
Matrix 2:
[2 3 5 8 5]
Addition:
[ 2  6  5 10 11]
Subtraction:
[-2  0 -5 -6  1]
Multiplication:
[ 0  9  0 16 30]


# 6 Two random vectors of size 7, dot product.

In [9]:
vector_1 = np.random.rand(7)
vector_2 = np.random.rand(7)

result = np.dot(vector_1, vector_2)
print(f'The dot product of two vectors:')
print(f'{result:.2f}')

The dot product of two vectors:
1.75


# 7 Two random matrices of size 2x2 and 2x3, integers between 1 and 10, multiplication.

In [11]:
matrix_1 = np.random.randint(1, 10, size=(2,2))
matrix_2 = np.random.randint(1, 10, size=(2,3))

mult = np.dot(matrix_1, matrix_2)
print(f'Multiplication of two matrix 2x2 and 2x3:')
print(mult)

Multiplication of two matrix 2x2 and 2x3:
[[38 36 22]
 [65 59 37]]
